#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
